# Generated by Django 4.2.26 on 2025-11-15 03:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('delete_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('delete_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/dishes/', verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'Plato',
                'verbose_name_plural': 'Platos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FoodTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('delete_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Etiqueta alimentaria',
                'verbose_name_plural': 'Etiquetas alimentarias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('delete_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('capacity', models.PositiveIntegerField(help_text='Número máximo de comensales que puede acomodar la mesa.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Capacidad')),
            ],
            options={
                'verbose_name': 'Mesa',
                'verbose_name_plural': 'Mesas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('delete_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('customer_name', models.CharField(max_length=150, verbose_name='Nombre del cliente')),
                ('reservation_datetime', models.DateTimeField(verbose_name='Fecha y hora de la reserva')),
                ('number_of_guests', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Número de comensales')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='restaurant.table', verbose_name='Mesa')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-reservation_datetime'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('delete_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('READY', 'Listo'), ('DELIVERED', 'Entregado')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Pagado')),
                ('customer_name', models.CharField(help_text='Cliente que consume y puede ocupar múltiples mesas', max_length=150, verbose_name='Nombre del cliente')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, help_text='Sumatoria de todos los platos del pedido', max_digits=10, verbose_name='Monto total')),
                ('dishes', models.ManyToManyField(related_name='orders', to='restaurant.dish', verbose_name='Platos')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='restaurant.table', verbose_name='Mesa')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('delete_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('dishes', models.ManyToManyField(blank=True, related_name='menus', to='restaurant.dish', verbose_name='Platos')),
            ],
            options={
                'verbose_name': 'Menú',
                'verbose_name_plural': 'Menús',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='dish',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='dishes', to='restaurant.foodtag', verbose_name='Etiquetas'),
        ),
    ]
