# Generated by Django 4.2.26 on 2025-11-17 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('delete_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Etiqueta alimentaria',
                'verbose_name_plural': 'Etiquetas alimentarias',
                'db_table': 'savoro_food_tag',
                'ordering': ['name'],
            },
        ),
    ]
