# Generated by Django 4.2.26 on 2025-12-01 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='savoro_category',
        ),
    ]
