# Generated by Django 4.2.26 on 2025-11-17 16:39

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('food_tag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('delete_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio')),
                ('image', models.ImageField(blank=True, null=True, upload_to='dishes/', verbose_name='Imagen')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dishes', to='category.category', verbose_name='Categoría')),
                ('tags', models.ManyToManyField(blank=True, db_table='savoro_dish_tags', related_name='dishes', to='food_tag.foodtag', verbose_name='Etiquetas')),
            ],
            options={
                'verbose_name': 'Plato',
                'verbose_name_plural': 'Platos',
                'ordering': ['name'],
            },
        ),
    ]
